# Generated by Django 5.2.4 on 2025-10-23 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(default='Desconocido', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('age', models.PositiveIntegerField()),
                ('race', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubication', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('timetable', models.TextField(default='[]', null=True)),
                ('FC', models.FloatField()),
                ('WC', models.FloatField()),
                ('FP', models.BooleanField(default=False)),
                ('WP', models.BooleanField(default=False)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensers', to='api.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensers', to='api.user')),
            ],
        ),
    ]
