# Generated by Django 5.2.4 on 2025-11-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispenser',
            name='FP',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dispenser',
            name='WP',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dispenser',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
